-- MySQL Script generated by MySQL Workbench
-- Mon Nov 28 15:57:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sistema_Estoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Sistema_Estoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sistema_Estoque` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
USE `Sistema_Estoque` ;

-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`categoria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`codigo_barra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`codigo_barra` (
  `cod` INT NOT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`produto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `q_estoque` INT NOT NULL,
  `valor_venda` DECIMAL(5,2) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `categoria` INT UNSIGNED NOT NULL,
  `codigo_barra` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria`)
    REFERENCES `Sistema_Estoque`.`categoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produto_codigo_barra1`
    FOREIGN KEY (`codigo_barra`)
    REFERENCES `Sistema_Estoque`.`codigo_barra` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`nivel_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`nivel_usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nivel` TINYINT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`usuario` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(225) NOT NULL UNIQUE,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `senha` VARCHAR(255) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nivel_usuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idusuario`),
  CONSTRAINT `fk_usuario_nivel_usuario1`
    FOREIGN KEY (`nivel_usuario`)
    REFERENCES `Sistema_Estoque`.`nivel_usuario` (`id`)
    ON UPDATE CASCADE
    ON DELETE CASCADE
    )ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`saida_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`saida_estoque` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `justificativa` TEXT NOT NULL,
  `voltou` ENUM('YES', 'NOT') NOT NULL DEFAULT 'NOT',
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `quantidade` INT NOT NULL,
  `usuario` INT UNSIGNED NOT NULL,
  `produto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_saida_estoque_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `Sistema_Estoque`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_saida_estoque_produto1`
    FOREIGN KEY (`produto`)
    REFERENCES `Sistema_Estoque`.`produto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`forma_pagamento` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `contacto` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `nascimento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`conta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `total` DECIMAL(5,2) NOT NULL,
  `valor_pago` DECIMAL(5,2) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario` INT UNSIGNED NOT NULL,
  `forma_pagamento` INT UNSIGNED NOT NULL,
  `cliente` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_conta_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `Sistema_Estoque`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_conta_forma_pagamento1`
    FOREIGN KEY (`forma_pagamento`)
    REFERENCES `Sistema_Estoque`.`forma_pagamento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_conta_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `Sistema_Estoque`.`cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`prato_dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`prato_dia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`item_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`item_venda` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `produto` INT UNSIGNED NULL,
  `conta` INT UNSIGNED NOT NULL,
  `prato_dia` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_item_venda_produto1`
    FOREIGN KEY (`produto`)
    REFERENCES `Sistema_Estoque`.`produto` (`id`)
   ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_item_venda_conta1`
    FOREIGN KEY (`conta`)
    REFERENCES `Sistema_Estoque`.`conta` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_item_venda_prato_dia1`
    FOREIGN KEY (`prato_dia`)
    REFERENCES `Sistema_Estoque`.`prato_dia` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`saida_conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`saida_conta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(5,2) NOT NULL,
  `justificativa` TEXT NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `conta` INT UNSIGNED NOT NULL,
  `usuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_saida_conta_conta1`
    FOREIGN KEY (`conta`)
    REFERENCES `Sistema_Estoque`.`conta` (`id`)
   ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_saida_conta_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `Sistema_Estoque`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`fornecedor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `contacto` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `endereco` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`entrada_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`entrada_estoque` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `valor_pago` DECIMAL(5,2) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `produto` INT UNSIGNED NOT NULL,
  `usuario` INT UNSIGNED NOT NULL,
  `fornecedor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_entrada_estoque_produto1`
    FOREIGN KEY (`produto`)
    REFERENCES `Sistema_Estoque`.`produto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entrada_estoque_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `Sistema_Estoque`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entrada_estoque_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `Sistema_Estoque`.`fornecedor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`escola` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(225) NOT NULL UNIQUE,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `senha` VARCHAR(255) NOT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_Estoque`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema_Estoque`.`pedido` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conta` INT NOT NULL,
  `produto` INT UNSIGNED NULL,
  `prato_dia` INT UNSIGNED NULL,
  `escola` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pedido_produto1`
    FOREIGN KEY (`produto`)
    REFERENCES `Sistema_Estoque`.`produto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_prato_dia1`
    FOREIGN KEY (`prato_dia`)
    REFERENCES `Sistema_Estoque`.`prato_dia` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_escola1`
    FOREIGN KEY (`escola`)
    REFERENCES `Sistema_Estoque`.`escola` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
